### ISSUE TITLE
SNS topic does not meet security best practices

### ISSUE THREAD

**Issue by MaksimAniskov** [aws-samples/aws-security-hub-summary-email#1]
SNS topic does not meet AWS Foundational Security Best Practices standard's requirement [[SNS.1] SNS topics should be encrypted at rest using AWS KMS](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-sns-1).

**Comment by jcriswell** [comment]
Addressed in latest commit.
