### ISSUE TITLE
Cannot render the template because of an error.: YAMLException: end of the stream or a document separator is expected at line 136, column 65: ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... ^

### ISSUE THREAD

**Issue by EdmundChuah-RMIT** [aws-samples/aws-security-hub-summary-email#3]
There seems to be an error when uploading the _security-hub-email-summary-cf-template.json_ file to CloudFormation.

**Comment by jcriswell** [comment]
I'm not getting the same error. based on the error having encoding in it, is it possible you downloaded the template as HTML (from github) and then named it .json.  try recreating the json file by copying the RAW code 

https://raw.githubusercontent.com/aws-samples/aws-security-hub-summary-email/main/security-hub-email-summary-cf-template.json

Let me know if the issue persists.
