### ISSUE TITLE
Send Security Hub Findings to reletive account

### ISSUE THREAD

**Issue by devalibvr** [aws-samples/aws-security-hub-summary-email#6]
Hi,

This is only a question. I wonder if there's a way that I can  filter findings based on account IDs and send them to the right accounts based on their account IDs?

Thanks
Ali

**Comment by jcriswell** [comment]
@devalibvr , I'm not sure if you are referring to this recurring email solution or something else?

For this email solution you could customize the custom insights for specific accounts.  Depending on the amount of accounts you have that could be a lot of custom insights to manage.

If you mean for solution that sends a notification when the finding is discovered, one solution could be to setup an eventBridge rule with SNS to notify an account holder of a new or changed Security Hub finding - https://repost.aws/questions/QUJu7GM_ltS_unhhrEVleKCg/how-to-receive-email-alert-when-compliance-status-changes-to-failed-for-particular-test-in-security-hub
