### ISSUE TITLE
Error in JSON file - security-hub-email-summary-cf-template.json

### ISSUE THREAD

**Issue by surendarbalaraman** [aws-samples/aws-security-hub-summary-email#8]
While provisioning in cloudformation stacksets getting the following error when uploading the file security-hub-email-summary-cf-template.json from S3 bucket.  
<img width="213" alt="githuberr" src="https://github.com/aws-samples/aws-security-hub-summary-email/assets/152376353/7f9a1b24-0ada-46f0-9ff2-0dd92f04b98f">

Kindly help to resolve the above issue

**Comment by jcriswell** [comment]
download the json in the raw view:

https://raw.githubusercontent.com/aws-samples/aws-security-hub-summary-email/main/security-hub-email-summary-cf-template.json

when you copy / paste otherwise it can get HTML in it.
